### ISSUE TITLE
main.py cannot import sscanss module

### ISSUE THREAD

**Issue by franzlang** [ISISNeutronMuon/SScanSS-2#1]
When following the installation instructions the following error is returned when running `python3 main.py` :
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from sscanss.config import setup_logging, STATIC_PATH, IMAGES_PATH
ModuleNotFoundError: No module named 'sscanss'
```

**Comment by StephenNneji** [comment]
Sorry for the late reply, I did not get any notification

You need to add the code below to main.py after ```import sys```. IDEs like PyCharm can handle this without modifying the code

```
import os
sys.path.append(os.path.abspath('.')) 
```
